on:
  push:
    branches:
      - 'main'

jobs:
  validate-api:
    runs-on: ubuntu-latest
    name: Validate API with rulesets
    steps:
    - uses: actions/checkout@v6
    - uses: ibm-apiconnect/governance@v12
      with:
        manager-host: api-manager.us-east-b.apiconnect.automation.ibm.com
        api-host: platform-api.us-east-b.apiconnect.automation.ibm.com
        provider-org: 'ricky'
        apikey: ${{ secrets.apikey }}
        api-spec: 'orders-api/order-status-api-spec.yml'
  deploy-api-sandbox:
    runs-on: ubuntu-latest
    needs: validate-api
    name: Deploy API to Sandbox
    steps:
    - uses: actions/checkout@v6
    - uses: ibm-apiconnect/deploy@v12
      with:
        manager-host: api-manager.us-east-b.apiconnect.automation.ibm.com
        api-host: platform-api.us-east-b.apiconnect.automation.ibm.com
        provider-org: 'ricky'
        catalog: 'sandbox'
        apikey: ${{ secrets.apikey }}
        project: 'orders-api'
  test-api:
    runs-on: ubuntu-latest
    needs: deploy-api-sandbox
    name: Functional Test
    steps:
    - uses: actions/checkout@v6
    - uses: ibm-apiconnect/testing@v12
      with:
        manager-host: api-manager.us-east-b.apiconnect.automation.ibm.com
        api-host: platform-api.us-east-b.apiconnect.automation.ibm.com
        provider-org: 'ricky'
        catalog: 'sandbox'
        apikey: ${{ secrets.apikey }}
        project: 'orders-api'
        test-name: orders-api:successful-lookup:1.0
        test-endpoint: 'https://order-sandbox-ricky.api-n-ea7a.us-east-b.apiconnect.ibmappdomain.cloud/1.0/orders/order'
  load-test-api:
    needs: deploy-api-sandbox
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./loadtest/api*.js        
  deploy-api-preprod:
    runs-on: ubuntu-latest
    needs: [test-api, load-test-api]
    name: Deploy API to UAT
    steps:
    - uses: actions/checkout@v6
    - uses: ibm-apiconnect/deploy@v12
      with:
        manager-host: api-manager.us-east-b.apiconnect.automation.ibm.com
        api-host: platform-api.us-east-b.apiconnect.automation.ibm.com
        provider-org: 'ricky'
        catalog: 'sandbox'
        apikey: ${{ secrets.apikey }}
        project: 'orders-api'